# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(662, 440)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.principal = QtWidgets.QFrame(parent=self.centralwidget)
        self.principal.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.principal.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.principal.setLineWidth(1)
        self.principal.setObjectName("principal")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.principal)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.imagenes = QtWidgets.QFrame(parent=self.principal)
        self.imagenes.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.imagenes.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.imagenes.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.imagenes.setObjectName("imagenes")
        self.mostrar_img1 = QtWidgets.QPushButton(parent=self.imagenes)
        self.mostrar_img1.setGeometry(QtCore.QRect(70, 370, 181, 24))
        self.mostrar_img1.setStyleSheet("background-color: rgb(200,0,0)\n"
"")
        self.mostrar_img1.setObjectName("mostrar_img1")
        self.mostrar_imagen1 = QtWidgets.QLabel(parent=self.imagenes)
        self.mostrar_imagen1.setGeometry(QtCore.QRect(60, 50, 171, 101))
        self.mostrar_imagen1.setObjectName("mostrar_imagen1")
        self.mostrar_imagen2 = QtWidgets.QLabel(parent=self.imagenes)
        self.mostrar_imagen2.setGeometry(QtCore.QRect(60, 190, 171, 91))
        self.mostrar_imagen2.setObjectName("mostrar_imagen2")
        self.horizontalLayout_2.addWidget(self.imagenes)
        self.resultado = QtWidgets.QFrame(parent=self.principal)
        self.resultado.setStyleSheet("background-color: rgb(200,0,10)")
        self.resultado.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.resultado.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.resultado.setObjectName("resultado")
        self.imagen_resultado = QtWidgets.QLabel(parent=self.resultado)
        self.imagen_resultado.setGeometry(QtCore.QRect(60, 60, 341, 271))
        self.imagen_resultado.setObjectName("imagen_resultado")
        self.horizontalLayout_2.addWidget(self.resultado)
        self.horizontalLayout.addWidget(self.principal)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.mostrar_img1.setText(_translate("MainWindow", "Imagenes"))
        self.mostrar_imagen1.setText(_translate("MainWindow", "TextLabel"))
        self.mostrar_imagen2.setText(_translate("MainWindow", "TextLabel"))
        self.imagen_resultado.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
